# Generated by Django 5.1.4 on 2025-01-13 19:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='request',
            name='unique_sender_receiver_pair',
        ),
        migrations.RemoveConstraint(
            model_name='request',
            name='unique_receiver_sender_pair',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 1, 13, 19, 3, 39, 178140, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversationsettings',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_settings', to='apps.profile'),
        ),
    ]
