# Generated by Django 5.1.4 on 2025-01-13 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=datetime.datetime(2025, 1, 13, 17, 26, 58, 79344, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
