# Generated by Django 5.1.5 on 2025-01-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_request_unique_sender_receiver_pair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
