# Generated by Django 5.1.4 on 2025-01-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsettings',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_settings', to='apps.profile'),
        ),
    ]
