# Generated by Django 5.1.4 on 2025-01-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_conversationsettings_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.conversation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.profile')),
            ],
            options={
                'verbose_name': 'Conversation Profile',
                'verbose_name_plural': 'Conversation Profiles',
                'unique_together': {('conversation', 'profile')},
            },
        ),
        migrations.AlterField(
            model_name='conversation',
            name='profiles',
            field=models.ManyToManyField(related_name='conversations', through='apps.ConversationProfile', to='apps.profile'),
        ),
    ]
