# Generated by Django 5.1.6 on 2025-02-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forward',
            field=models.ManyToManyField(blank=True, null=True, related_name='forward_messages', to='apps.conversation'),
        ),
    ]
