# Generated by Django 5.0.6 on 2025-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_profile_first_name_alter_profile_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked'), ('deleted', 'Deleted'), ('hidden', 'Hidden')], default='pending', max_length=10),
        ),
    ]
