# Generated by Django 5.1.6 on 2025-02-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_message_forwarded_from_message_is_forwarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachments',
            name='message',
        ),
    ]
