# Generated by Django 5.1.6 on 2025-02-16 17:28

import apps.media_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_attachments_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ManyToManyField(related_name='messages', to='apps.attachments'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file',
            field=models.FileField(storage=apps.media_storage.MediaStorage(), upload_to='chat_media/'),
        ),
    ]
