# Generated by Django 5.1.6 on 2025-02-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_message_file_alter_attachments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachments',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attachments',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
